version: 2
updates:
- package-ecosystem: bundler
  directory: /
  schedule:
    interval: weekly
  pull-request-branch-name:
    separator: "-"
  groups:
    bundler-dependencies:
      patterns:
      - "*"
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
- package-ecosystem: bundler
  directory: /sample
  schedule:
    interval: weekly
  pull-request-branch-name:
    separator: "-"
  groups:
    bundler-dependencies:
      patterns:
      - "*"
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
- package-ecosystem: pip
  directory: /docs
  schedule:
    interval: weekly
  pull-request-branch-name:
    separator: "-"
  groups:
    pip-dependencies:
      patterns:
      - "*"
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
