---
AllCops:
  TargetRubyVersion: 3.3.4
  Exclude:
    - '.gemspec'
    - 'vendor/**/*'
    - 'sample/bin/aws-codedeploy-samples/**/*'
    - 'sample/gems/**/*'
    - 'spec/**/*'
    - 'lib/default/**/*'
Metrics/AbcSize:
  Max: 35
Metrics/BlockLength:
  Max: 35
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Max: 120
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ClassLength:
  Max: 130
Style/Documentation:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Lint/EmptyFile:
  Enabled: false