---
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - '.gemspec'
    - 'vendor/**/*'
    - 'sample/bin/aws-codedeploy-samples/**/*'
    - 'sample/gems/**/*'
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Max: 100
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ClassLength:
  Max: 130
Style/Documentation:
  Enabled: false
