---
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - '.gemspec'
    - 'vendor/**/*'
    - 'sample/bin/aws-codedeploy-samples/**/*'
    - 'sample/gems/**/*'
    - 'spec/**/*'
    - 'lib/default/**/*'
Metrics/AbcSize:
  Max: 35
Metrics/BlockLength:
  Max: 35
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Max: 120
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ClassLength:
  Max: 130
Style/Documentation:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
