---
language: ruby

cache: bundler
# This will enable the container-based infrastructure for
# travis tests. It should result in faster test vm load times.
# @see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

before_install:
  - gem update --system
  - gem update bundler

rvm:
  - 2.2
  - 2.3.3
