site_name: Moonshot
theme: 'mkdocs'
pages:
- Home: 'index.md'
- Example: example.md
- User Guide:
  - 'CLI Commands': 'user-guide/cli.md'
  - 'Including Moonshot in your project': 'user-guide/include_in_your_project.md'
  - 'Working with parent stacks': 'user-guide/parent_stacks.md'
  - 'Stack parameter strategies': 'user-guide/stack_parameter_strategies.md'
- Mechanisms:
  - 'Artifact Repository': 'mechanisms/artifact-repository.md'
  - 'Build': 'mechanisms/build.md'
  - 'Deployment': 'mechanisms/deployment.md'
- Plugins: plugins.md
- Bundled plugins:
  - 'Backup plugin': 'plugins/backup.md'
- About:
  - 'How to Contribute': 'about/contribute.md'
  - 'License': 'about/license.md'
